# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FS-5B81lonKUIvcBMVq2bG4ZWdOGFxU
"""

# streamlit_app.py
import streamlit as st

# Base URL for raw user content in GitHub
base_url = 'https://github.com/kritinkesavkts/ProjectSDV/blob/main/'

# List of image filenames for 15 visualizations
image_filenames = [f"{i}.jpg?raw=true" for i in range(1, 16)]

# Title of your gallery
st.title('Visualization Gallery')

# Display each image with the corresponding caption
for i, filename in enumerate(image_filenames):
    image_url = f"{base_url}{filename}"
    st.image(image_url, caption=f'Visualization {i+1}', use_column_width=True)